### ISSUE TITLE
Interface Finalisation

### ISSUE THREAD

**Issue by davidwarne** [haji-ali/oxford-mlmc-c#4]
I have had a look at the interface header, Its about what I would expect.

Do you think that the user functions, instead of being a typedef could be an element of the mlmc_options structure? This could simplify the MLMC driver interface.

E.g.,

typedef struct s_mlmc_options{
    unsigned int Lmin;  // Minimum number of levels
    unsigned int Lmax;  // Maximum number of levels

    unsigned long long N0;   // Initial number of samples to compute variance estimates

    double alpha;             // Weak convergence rate. Must be positive
    double beta;              // Variance convergence rate. Must be positive
    double gamma;             // Work rate. Must be positive

    // It will be difficult to support variable length vectors efficiently.
    // I think we should focus on fixed length vectors for now.
    unsigned int per_sample;  // Vector length for vector quantities
   
    void *user_data;
    void (*fn_mlmc_sample_levels)(unsigned int L,
                                   const unsigned long long* M,
                                   double *sums,
                                   unsigned int sums_size,
                                   void *user_data);
    void (*fn_mlmc_sample_level)(unsigned int ell,
                                  unsigned long long M,
                                  double *sums,
                                  unsigned int sums_size,
                                  void *user_data);
} mlmc_options;

Also do you think we should have a flag in the options to make the driver  ignore alpha, beta and gamma and perform trial simulations to approximate the compute time and variance of each level?
Just thoughts...

**Comment by haji-ali** [comment]
I agree with both suggestions. 
I was thinking that mlmc_options would be optional while the sampling function would be required. 
But I guess we can just make MLMCCreateOptions take the function handle as an argument to ensure that it is initialized correctly.

Feel free to make those changes when you have a chance.

**Comment by haji-ali** [comment]
I just had a chance to see your changes. A few points:
1. As far as I could see the GNU standard has function names like this mlmc_run, instead of MLMCRun. Do you agree?
2. Is there a reason why you make mlmc_create_options take extra arguments (Lmin, Lmax, N0, ...)? My idea was not asking the user for these arguments and instead having them set to some default reasonable value. So I was thinking mlmc_create_options would only take the arguments for which no default value is possible (like sample_lvl).
3. Either fn_mlmc_sample_levels or fn_mlmc_sample_level is needed and they are mutually exclusive. So I created another function mlmc_create_options_simple which takes the single level sampler as an argument. Let me know what you think.

If you agree with these changes we can go ahead and start updating mlmc.cpp.
One thing is to not use C++ features like references (and change the name to mlmc.c).

**Comment by davidwarne** [comment]
Hi Abdo,

1. Yes I believe you are correct. Thanks for making that change. and the typedef for the function pointers was a good idea too.
2. My idea for the args for mlmc_create_options was to provide a controlled way for users to populate the mlmc_options struct. If you'd prefer that the mlmc_options simply be set to defaults at creation, then I recommend we have a second function that sets members rather than have the user manually set members.
3. Ok I was not sure about the use case here. I figured the unused functions would just be set to NULL.
4. Something I would like to do is add detailed comments in doxygen style to the header file, I'll try too get to this early next week.

**Comment by haji-ali** [comment]
I think the interface looks finalized, at least for now. I also added the documentation of all functions. If everything is finalized we can start with the implementation.

**Comment by davidwarne** [comment]
Great. I've added the current contributing authors to the header comments. This issue can probably be closed now.
